---
title: "Summary statistics of all matches"
author: "Dr. Jürgen Walther"
date: "9/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(xlsx)
library(dplyr)
library(gridExtra)
library(grid)

devtools::load_all()
```



```{r combine summary statistics, warning=FALSE,message=FALSE, echo=FALSE}

path <- "C://Users/Juergis/Documents/Fussball/Spielanalyse/Programm/Videoanalyse/WFV"


stat_files <- list.files(path = paste0(path, "/Statistik/"), pattern = "*Rdata", full.names = TRUE)

load(stat_files[1])
st_load <- summary_table
spiel_load <- spiel
for (i in 2:length(stat_files)) {
  load(stat_files[i])
  st_load <- cbind(st_load, summary_table[, 2])
  spiel_load <- c(spiel_load, spiel)
}

red_match_names <- table_shorten_match_name(match_names = spiel_load)

colnames(st_load) <- c("Parameter", red_match_names)
# Im Seligenporten-Spiel wurden keine Ecken gezählt
st_load[c(nrow(st_load) - 1, nrow(st_load)), 2] <- c(NA, NA)

# Save table
xlsx::write.xlsx(x = st_load, file = paste0(path, "/Statistik/Zusammenfassung/", Sys.Date(), "_Statistiken_kombiniert.xlsx"), row.names = FALSE)

df_st_load <- as.data.frame(st_load)
df_st_load <- df_st_load %>% dplyr::mutate_if(is.list, as.character)

# For every match add 100 in width
png(file = paste0(path, "/Statistik/Zusammenfassung/", Sys.Date(), "_Statistiken_kombiniert.png"), height = 800, width = 650 + length(stat_files) * 45)
gridExtra::grid.table(df_st_load, rows = NULL)
dev.off()
```
