---
title: "Spielanalyse Zusammenfassung"
author: "Dr. Jürgen Walther"
date: "9/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load packages, warning=FALSE,message=FALSE, echo=FALSE}
# Main modules
library(dplyr)
library(ggplot2)
library(data.table)
# Modules for specific functions
library(tidyr)
# Plot moduless
library(pracma)
library(MASS)
library(ggforce)
library(cowplot)
# Write files modules
library(xlsx)
library(gridExtra)
# Load footballmatchanalysis
install.packages("C:/Users/Juergis/Documents/Fussball/Spielanalyse/Programm/Software/repo/footballmatchanalysis_0.1.0.tar.gz", repos = NULL, type = "source")
library(footballmatchanalysis)
```

# Daten laden

```{r load data, warning=FALSE,message=FALSE, echo=FALSE}

path <- "C://Users/Juergis/Documents/Fussball/Spielanalyse/Programm/Videoanalyse/WFV"

# Folder name of match analysis
spiel <- "20200905_Seligenporten-WFV"

# Number of sections to divide match analysis
n_sections <- 6

# Which plots do I want to plot?
plot_heatmaps_sections <- FALSE
plot_heatmap <- TRUE
plot_heatmap_discrete <- FALSE
plot_raw_data <- FALSE

# Spielrichtung im realen Spiel
spielrichtung_real <- c(rep("r", 3), rep("l", 3)) # Die Spielrichtung in der Analyse ist immer von links nach rechts, also "r". Bei anderer Spielrichtung wird das Feld gespiegelt.

filenames <- c("paesse", "schuesse", "schuesse_gegner")

all_data <- lapply(filenames, function(file) {
  footballmatchanalysis::load_all_sections(
    filename = file,
    spiel = spiel,
    path = path,
    num_sections = n_sections
  )
})



```

# Variablen definieren

```{r important variables, warning=FALSE,message=FALSE, echo=FALSE}

outfolder <- paste0(path, "/", spiel, "/Analyse")
# dir.create(outfolder, showWarnings = TRUE)

outfolder_pass <- paste0(outfolder,"/Paesse")
outfolder_balls <- paste0(outfolder,"/Balluebernahme")
outfolder_shots <- paste0(outfolder,"/Schuesse")
outfolder_tactics <- paste0(outfolder,"/Taktik")

arrhead <- "last"
```

# Normalize and mirror data

```{r mirror data, warning=FALSE,message=FALSE, echo=FALSE}

all_data_norm_mirrored <- lapply(1:length(all_data), function(i) {
  lapply(1:length(all_data[[i]]), function(x) {
    footballmatchanalysis::mirror_sequences(
      footballmatchanalysis::normalize_sequences(all_data[[i]][[x]]),
      spielrichtung_real = spielrichtung_real[x]
    )
  })
})

pass <- all_data_norm_mirrored[[1]]
shots <- all_data_norm_mirrored[[2]]
shots_opp <- all_data_norm_mirrored[[3]]
```



```{r create total data.frame, warning=FALSE,message=FALSE, echo=FALSE}

pass_tot <- merge_sequences(pass)

```

```{r plot passes}
if(isTRUE(plot_heatmaps_sections)){
for (i in 1:n_sections) {
  plot_pass_heatmap(
    df = pass[[i]],
    outpath = outfolder_pass,
    title_heatmap = "Heatmap der Pässe", 
    subtitle_heatmap = paste0("Spielabschnitt ",i),
    title_discrete = "Heatmap der Pässe",
    subtitle_discrete = paste0("Häufigkeit der Pässe im Spielabschnitt ",i),
    title_raw = "Passstafetten", 
    subtitle_raw = paste0("Spielabschnitt ",i),
    name_heatmap = paste0("paesse_heatmap_", i),
    name_discrete = paste0("paesse_heatmap_diskret_", i),
    name_raw = paste0("paesse_rawdata_", i),
    plot_heatmap = plot_heatmap, 
    plot_discrete = plot_discrete, 
    plot_rawdata = plot_raw_data
  )
}
}

plot_pass_heatmap(
    df = pass_tot,
    outpath = outfolder_pass,
    title_heatmap = "Heatmap der Pässe", 
    subtitle_heatmap = paste0("Gesamtes Spiel"),
    title_discrete = "Heatmap der Pässe",
    subtitle_discrete = paste0("Häufigkeit der Pässe im gesamten Spiel"),
    title_raw = "Passstafetten", 
    subtitle_raw = paste0("Gesamtes Spiel"),
    name_heatmap = paste0("paesse_heatmap_total"),
    name_discrete = paste0("paesse_heatmap_diskret_total"),
    name_raw = paste0("paesse_rawdata_total"),
    plot_heatmap = plot_heatmap, 
    plot_discrete = plot_heatmap_discrete, 
    plot_rawdata = plot_raw_data
  )
```
```{r passes between areas}

areas <- define_areas()


# Passes of defenders
rvm <- do.call("rbind", lapply(1:(nrow(pass_tot) - 1), get_passes_between_areas, pass_tot, areas$rv, areas$m))
rvrm <- do.call("rbind", lapply(1:(nrow(pass_tot) - 1), get_passes_between_areas, pass_tot, areas$rv, areas$rm))
lvm <- do.call("rbind", lapply(1:(nrow(pass_tot) - 1), get_passes_between_areas, pass_tot, areas$lv, areas$m))
lvlm <- do.call("rbind", lapply(1:(nrow(pass_tot) - 1), get_passes_between_areas, pass_tot, areas$lv, areas$lm))

# Passes of midfield
mrm <- do.call("rbind", lapply(1:(nrow(pass_tot) - 1), get_passes_between_areas, pass_tot, areas$m, areas$rm))
mlm <- do.call("rbind", lapply(1:(nrow(pass_tot) - 1), get_passes_between_areas, pass_tot, areas$m, areas$lm))

pass_areas_tot <- list(rvm = rvm, rvrm = rvrm, lvm = lvm, lvlm = lvlm, mrm = mrm, mlm = mlm)


```

```{r plot passes between areas}

plot_passes_between_areas(
  df = rvm,
  pos1 = areas$rv,
  pos2 = areas$m,
  title = "Pässe von Rechtsverteidiger zu zentralem Mittelfeld",
  outpath = outfolder_tactics,
  filename = "rv_to_m_total"
)

plot_passes_between_areas(
  df = rvrm,
  pos1 = areas$rv,
  pos2 = areas$rm,
  title = "Pässe von Rechtsverteidiger zu rechter Außenbahn",
  outpath = outfolder_tactics,
  filename = "rv_to_rm_total"
)

plot_passes_between_areas(
  df = lvm,
  pos1 = areas$lv,
  pos2 = areas$m,
  title = "Pässe von Linksverteidiger zu zentralem Mittelfeld",
  outpath = outfolder_tactics,
  filename = "lv_to_m_total"
)

plot_passes_between_areas(
  df = lvlm,
  pos1 = areas$lv,
  pos2 = areas$lm,
  title = "Pässe von Linksverteidiger zu linker Außenbahn",
  outpath = outfolder_tactics,
  filename = "lv_to_lm_total"
)

plot_passes_between_areas(
  df = mlm,
  pos1 = areas$m,
  pos2 = areas$lm,
  title = "Pässe von zentralem Mittelfeld zu linker Außenbahn",
  outpath = outfolder_tactics,
  filename = "m_to_lm_total"
)

plot_passes_between_areas(
  df = mrm,
  pos1 = areas$m,
  pos2 = areas$rm,
  title = "Pässe von zentralem Mittelfeld zu rechter Außenbahn",
  outpath = outfolder_tactics,
  filename = "m_to_rm_total"
)
```



```{r plot balls}
# Get balls won and balls lost
ls_balls_lost <- lapply(pass, balls_lost)
ls_balls_won <- lapply(pass, balls_won)

# Get total balls won and total balls lost
balls_lost_tot <- merge_sequences(ls_balls_lost)
balls_won_tot <- merge_sequences(ls_balls_won)

for (i in 1:n_sections) {
  plot_balls(df = ls_balls_won[[i]], title = "Ballgewinne", subtitle = paste0("Position der Ballgewinne in Spielabschnitt ",i), outpath = outfolder_balls, filename = paste0("ballgewinne_", i))
  plot_balls(df = ls_balls_lost[[i]], title = "Ballverluste", subtitle = paste0("Position der Ballverluste in Spielabschnitt ",i), outpath = outfolder_balls, filename = paste0("ballverluste_", i))
}

plot_balls(df = balls_won_tot, title = "Ballgewinne", subtitle = paste0("Position der Ballgewinne im gesamten Spiel"), outpath = outfolder_balls, filename = paste0("ballgewinne_total"))
plot_balls(df = balls_lost_tot, title = "Ballverluste", subtitle = paste0("Position der Ballverluste im gesamten Spiel"), outpath = outfolder_balls, filename = paste0("ballverluste_total"))
```

```{r plot shots}

# Get total balls won and total balls lost
shots_tot <- merge_sequences(shots)
shots_opp_tot <- merge_sequences(shots_opp)

for (i in 1:n_sections) {
  plot_shots(df = shots[[i]], title = "Schüsse", subtitle = paste0("Position der Schüsse in Spielabschnitt ",i), outpath = outfolder_shots, filename = paste0("schuesse_", i))
  plot_shots(df = shots_opp[[i]], title = "Schüsse des Gegners", subtitle = paste0("Position der Schüsse des Gegners in Spielabschnitt ",i), outpath = outfolder_shots, filename = paste0("schuesse_gegner_", i))
}

plot_shots(df = shots_tot, title = "Schüsse", subtitle = paste0("Position der Schüsse im gesamten Spiel"), outpath = outfolder_shots, filename = paste0("schuesse_total"))
plot_shots(df = shots_opp_tot, title = "Schüsse des Gegners", subtitle = paste0("Position der Schüsse des Gegners im gesamten Spiel"), outpath = outfolder_shots, filename = paste0("schuesse_gegner_total"))
```


```{r summary statistics}

summary_table <- summary_table(pass = pass_tot, shots = shots_tot, shots_opp = shots_opp_tot, pass_areas = pass_areas_tot)
print(summary_table)
xlsx::write.xlsx(x = summary_table, file = paste0(outfolder,"/Zusammenfassung_Statistiken.xlsx"), row.names = FALSE)


df_st <- as.data.frame(summary_table)
df_st <- df_st  %>% dplyr::mutate_if(is.list, as.character)

jpeg(file = paste0(outfolder,"/Zusammenfassung_Statistiken.jpeg"))
gridExtra::grid.table(df_st, rows = NULL)
dev.off()

```
