---
title: "Spielanalyse Zusammenfassung"
author: "Dr. Jürgen Walther"
date: "9/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load packages, warning=FALSE,message=FALSE, echo=FALSE}
# Main modules
library(devtools)
library(dplyr)
library(ggplot2)
library(data.table)
# Read modules
library(readxl)
# Modules for specific functions
library(tidyr)
# Plot moduless
library(pracma)
library(MASS)
library(ggforce)
library(cowplot)
# Write files modules
library(xlsx)
library(gridExtra)
library(grid)
# Load footballmatchanalysis
# install.packages("C:/Users/Juergis/Documents/Fussball/Spielanalyse/Programm/Software/repo/footballmatchanalysis_0.2.0.tar.gz", repos = NULL, type = "source")
# library(footballmatchanalysis)
devtools::load_all()
```

# Variable Daten

```{r}
# Folder name of match analysis
spiel <- "20221112_WFV-Erlangen"

# Spielrichtung im realen Spiel
spielrichtung_real <- c(rep("r", 3), rep("l", 3)) # Die Spielrichtung in der Analyse ist immer von links nach rechts, also "r". Bei anderer Spielrichtung wird das Feld gespiegelt.
```


# Daten laden

```{r load data, warning=FALSE,message=FALSE, echo=FALSE}

parent_path <- "C://Users/Juergis/Documents/Fussball/Spielanalyse/Programm/Videoanalyse/WFV"
season <- "Saison2223"
path <- paste0(parent_path, "/", season)


# Number of sections to divide match analysis
n_sections <- 6

summarize_to_halfs <- TRUE
n_halfs <- 2
n_plot <- ifelse(summarize_to_halfs, n_halfs, n_sections)

# Which plots do I want to plot?
plot_heatmaps_sections <- FALSE
plot_heatmap <- TRUE
plot_heatmap_discrete <- FALSE
plot_raw_data <- FALSE
plot_shots_individual <- FALSE
plot_balls_individual <- FALSE

# Plot all matches
plot_all_matches <- FALSE


# Anzahl an Ecken vom Excel Sheet erhalten. Die Werte werden in summary_table() ausgegeben
files_xlsx <- list.files(paste0(path, "/", spiel), pattern = "\\.xlsx$", full.names = TRUE)
ecken_all <- get_corners(file = files_xlsx[length(files_xlsx)])
ecken <- ecken_all[1]
ecken_gegner <- ecken_all[2]

filenames <- c("paesse", "schuesse", "schuesse_gegner")

all_data <- lapply(filenames, function(file) {
  footballmatchanalysis::load_all_sections(
    filename = file,
    spiel = spiel,
    path = path,
    num_sections = n_sections
  )
})
```

# Variablen und Pfade definieren

```{r important variables, warning=FALSE,message=FALSE, echo=FALSE}

outfolder <- paste0(path, "/", spiel, "/Analyse")
# dir.create(outfolder, showWarnings = TRUE)

outfolder_pass <- paste0(outfolder, "/Paesse")
outfolder_balls <- paste0(outfolder, "/Balluebernahme")
outfolder_shots <- paste0(outfolder, "/Schuesse")
outfolder_tactics <- paste0(outfolder, "/Taktik")

arrhead <- "last"
```

# Normalize and mirror data

```{r mirror data, warning=FALSE,message=FALSE, echo=FALSE}

all_data_norm_mirrored <- lapply(1:length(all_data), function(i) {
  lapply(1:length(all_data[[i]]), function(x) {
    footballmatchanalysis::mirror_sequences(
      footballmatchanalysis::normalize_sequences(all_data[[i]][[x]]),
      spielrichtung_real = spielrichtung_real[x]
    )
  })
})

# summarize from number of analysed sections to halfs
if (isTRUE(summarize_to_halfs) & n_sections > 2) {
  all_data_norm_mirrored_sum <- lapply(all_data_norm_mirrored, function(x) {
    list(
      merge_sequences(list_sequence = x, n1 = 1, n2 = n_sections / 2),
      merge_sequences(list_sequence = x, n1 = n_sections / 2 + 1, n2 = n_sections)
    )
  })
} else {
  all_data_norm_mirrored_sum <- all_data_norm_mirrored
}

pass <- all_data_norm_mirrored_sum[[1]]
shots <- all_data_norm_mirrored_sum[[2]]
shots_opp <- all_data_norm_mirrored_sum[[3]]
```



```{r create total data.frame, warning=FALSE,message=FALSE, echo=FALSE}

pass_tot <- merge_sequences(pass)
```

```{r plot passes, warning=FALSE,message=FALSE, echo=FALSE}
if (isTRUE(plot_heatmaps_sections)) {
  for (i in 1:n_plot) {
    plot_pass_heatmap(
      df = pass[[i]],
      outpath = outfolder_pass,
      title_heatmap = "Heatmap der Pässe",
      subtitle_heatmap = paste0("Spielabschnitt ", i),
      title_discrete = "Heatmap der Pässe",
      subtitle_discrete = paste0("Häufigkeit der Pässe im Spielabschnitt ", i),
      title_raw = "Passstafetten",
      subtitle_raw = paste0("Spielabschnitt ", i),
      name_heatmap = paste0("paesse_heatmap_", i),
      name_discrete = paste0("paesse_heatmap_diskret_", i),
      name_raw = paste0("paesse_rawdata_", i),
      plot_heatmap = plot_heatmap,
      plot_discrete = plot_discrete,
      plot_rawdata = plot_raw_data
    )
  }
}

plot_pass_heatmap(
  df = pass_tot,
  outpath = outfolder_pass,
  title_heatmap = "Heatmap der Pässe",
  subtitle_heatmap = paste0("Gesamtes Spiel: ", spiel),
  title_discrete = "Heatmap der Pässe",
  subtitle_discrete = paste0("Häufigkeit der Pässe im gesamten Spiel"),
  title_raw = "Passstafetten",
  subtitle_raw = paste0("Gesamtes Spiel"),
  name_heatmap = paste0("paesse_heatmap_total"),
  name_discrete = paste0("paesse_heatmap_diskret_total"),
  name_raw = paste0("paesse_rawdata_total"),
  plot_heatmap = plot_heatmap,
  plot_discrete = plot_heatmap_discrete,
  plot_rawdata = plot_raw_data
)
```

```{r won space in pass sequences}

pass_space_won_tot <- get_won_space_pass_sequence(pass_tot)

plot_won_space(
  pass = pass_space_won_tot,
  histogram = FALSE,
  subtitle = "Gesamtes Spiel",
  outpath = outfolder_pass,
  filename = "Raumgewinn_vs_Anzahl_Paesse_total"
)
plot_won_space(
  pass = pass_space_won_tot,
  histogram = TRUE,
  subtitle = "Gesamtes Spiel",
  outpath = outfolder_pass,
  filename = "Histogramm_Raumgewinn_total"
)

pass_space_won <- lapply(pass, get_won_space_pass_sequence)

for (i in 1:length(pass_space_won)) {
  plot_won_space(
    pass = pass_space_won[[i]],
    subtitle = paste0("Halbzeit ", i),
    outpath = outfolder_pass,
    filename = paste0("Raumgewinn_vs_Anzahl_Paesse_", i)
  )
  plot_won_space(
    pass = pass_space_won[[i]],
    histogram = TRUE,
    subtitle = paste0("Halbzeit ", i),
    outpath = outfolder_pass,
    filename = paste0("Histogramm_Raumgewinn_", i)
  )
}
```



```{r passes between areas, warning=FALSE,message=FALSE, echo=FALSE}

areas <- define_areas()

pass_areas <- lapply(pass, function(x) all_passes_areas(pass = x, areas = areas, additional_passes = TRUE))

pass_areas_tot <- all_passes_areas(pass = pass_tot, areas = areas, additional_passes = TRUE)
```


```{r plot passes between areas, warning=FALSE,message=FALSE, echo=FALSE}

# Plot passes between areas for all sections to be plotted

for (i in 1:length(pass_areas))
{
  plot_passes_between_areas(
    df = pass_areas[[i]]$rvm,
    pos1 = areas$rv,
    pos2 = areas$m,
    title = "Pässe von Rechtsverteidiger zu zentralem Mittelfeld",
    subtitle = paste0("Halbzeit ", i),
    outpath = outfolder_tactics,
    filename = paste0("rv_to_m_", i)
  )


  plot_passes_between_areas(
    df = pass_areas[[i]]$rvrm,
    pos1 = areas$rv,
    pos2 = areas$rm,
    title = "Pässe von Rechtsverteidiger zu rechter Außenbahn",
    subtitle = paste0("Halbzeit ", i),
    outpath = outfolder_tactics,
    filename = paste0("rv_to_rm_", i)
  )

  plot_passes_between_areas(
    df = pass_areas[[i]]$lvm,
    pos1 = areas$lv,
    pos2 = areas$m,
    title = "Pässe von Linksverteidiger zu zentralem Mittelfeld",
    subtitle = paste0("Halbzeit ", i),
    outpath = outfolder_tactics,
    filename = paste0("lv_to_m_", i)
  )

  plot_passes_between_areas(
    df = pass_areas[[i]]$lvlm,
    pos1 = areas$lv,
    pos2 = areas$lm,
    title = "Pässe von Linksverteidiger zu linker Außenbahn",
    subtitle = paste0("Halbzeit ", i),
    outpath = outfolder_tactics,
    filename = paste0("lv_to_lm_", i)
  )

  plot_passes_between_areas(
    df = pass_areas[[i]]$mlm,
    pos1 = areas$m,
    pos2 = areas$lm,
    title = "Pässe von zentralem Mittelfeld zu linker Außenbahn",
    subtitle = paste0("Halbzeit ", i),
    outpath = outfolder_tactics,
    filename = paste0("m_to_lm_", i)
  )

  plot_passes_between_areas(
    df = pass_areas[[i]]$mrm,
    pos1 = areas$m,
    pos2 = areas$rm,
    title = "Pässe von zentralem Mittelfeld zu rechter Außenbahn",
    subtitle = paste0("Halbzeit ", i),
    outpath = outfolder_tactics,
    filename = paste0("m_to_rm_", i)
  )
}
```

```{r plot passes between areas total, warning=FALSE,message=FALSE, echo=FALSE}

# Plot passes between areas for whole match

plot_passes_between_areas(
  df = pass_areas_tot$rvm,
  pos1 = areas$rv,
  pos2 = areas$m,
  title = "Pässe von Rechtsverteidiger zu zentralem Mittelfeld",
  outpath = outfolder_tactics,
  filename = "rv_to_m_total"
)


plot_passes_between_areas(
  df = pass_areas_tot$rvrm,
  pos1 = areas$rv,
  pos2 = areas$rm,
  title = "Pässe von Rechtsverteidiger zu rechter Außenbahn",
  outpath = outfolder_tactics,
  filename = "rv_to_rm_total"
)

plot_passes_between_areas(
  df = pass_areas_tot$lvm,
  pos1 = areas$lv,
  pos2 = areas$m,
  title = "Pässe von Linksverteidiger zu zentralem Mittelfeld",
  outpath = outfolder_tactics,
  filename = "lv_to_m_total"
)

plot_passes_between_areas(
  df = pass_areas_tot$lvlm,
  pos1 = areas$lv,
  pos2 = areas$lm,
  title = "Pässe von Linksverteidiger zu linker Außenbahn",
  outpath = outfolder_tactics,
  filename = "lv_to_lm_total"
)

plot_passes_between_areas(
  df = pass_areas_tot$mlm,
  pos1 = areas$m,
  pos2 = areas$lm,
  title = "Pässe von zentralem Mittelfeld zu linker Außenbahn",
  outpath = outfolder_tactics,
  filename = "m_to_lm_total"
)

plot_passes_between_areas(
  df = pass_areas_tot$mrm,
  pos1 = areas$m,
  pos2 = areas$rm,
  title = "Pässe von zentralem Mittelfeld zu rechter Außenbahn",
  outpath = outfolder_tactics,
  filename = "m_to_rm_total"
)
```


```{r calculate balls won and lost, warning=FALSE,message=FALSE, echo=FALSE}
ls_balls_lost <- lapply(pass, balls_lost)
ls_balls_won <- lapply(pass, balls_won)

# Get total balls won and total balls lost
balls_lost_tot <- merge_sequences(ls_balls_lost)
balls_won_tot <- merge_sequences(ls_balls_won)
```



```{r plot balls, warning=FALSE,message=FALSE, echo=FALSE}
# Get balls won and balls lost
# Plot together
plot_all_sections(list_dfs = ls_balls_won, n_sections = n_plot, title = paste0("Ballgewinne WFV - ", spiel), outpath = outfolder_balls, filename = paste0("ballgewinne_combined"), parameter = "balls", size_points = 2.5)
plot_all_sections(list_dfs = ls_balls_lost, n_sections = n_plot, title = paste0("Ballverluste WFV - ", spiel), outpath = outfolder_balls, filename = paste0("ballverluste_combined"), parameter = "balls", size_points = 2.5)


# Plot individually
if (isTRUE(plot_balls_individual)) {
  for (i in 1:n_plot) {
    plot_balls(df = ls_balls_won[[i]], title = "Ballgewinne", subtitle = paste0("Position der Ballgewinne in Halbzeit ", i), outpath = outfolder_balls, filename = paste0("ballgewinne_", i))
    plot_balls(df = ls_balls_lost[[i]], title = "Ballverluste", subtitle = paste0("Position der Ballverluste in Halbzeit ", i), outpath = outfolder_balls, filename = paste0("ballverluste_", i))
  }
}

# Plot total balls won and lost
plot_balls(df = balls_won_tot, title = "Ballgewinne", subtitle = paste0("Position der Ballgewinne im gesamten Spiel"), outpath = outfolder_balls, filename = paste0("ballgewinne_total"))
plot_balls(df = balls_lost_tot, title = "Ballverluste", subtitle = paste0("Position der Ballverluste im gesamten Spiel"), outpath = outfolder_balls, filename = paste0("ballverluste_total"))
```

```{r calculate shots, warning=FALSE,message=FALSE, echo=FALSE}
# Get total balls won and total balls lost
shots_tot <- merge_sequences(shots)
shots_opp_tot <- merge_sequences(shots_opp)
```



```{r plot shots, warning=FALSE,message=FALSE, echo=FALSE}

# Plot together
plot_all_sections(list_dfs = shots, n_sections = n_plot, title = paste0("Schüsse WFV - ", spiel), outpath = outfolder_shots, filename = paste0("schuesse_combined"), parameter = "shots", size_points = 2.5)
plot_all_sections(list_dfs = shots_opp, n_sections = n_plot, title = paste0("Schüsse Gegner - ", spiel), outpath = outfolder_shots, filename = paste0("schuesse_gegner_combined"), parameter = "shots", size_points = 2.5)

# Plot individually
if (isTRUE(plot_shots_individual)) {
  for (i in 1:n_plot) {
    plot_shots(df = shots[[i]], title = "Schüsse", subtitle = paste0("Position der Schüsse in Spielabschnitt ", i), outpath = outfolder_shots, filename = paste0("schuesse_", i))
    plot_shots(df = shots_opp[[i]], title = "Schüsse des Gegners", subtitle = paste0("Position der Schüsse des Gegners in Spielabschnitt ", i), outpath = outfolder_shots, filename = paste0("schuesse_gegner_", i))
  }
}

# Plot total shots
plot_shots(df = shots_tot, title = "Schüsse", subtitle = paste0("Position der Schüsse im gesamten Spiel"), outpath = outfolder_shots, filename = paste0("schuesse_total"))
plot_shots(df = shots_opp_tot, title = "Schüsse des Gegners", subtitle = paste0("Position der Schüsse des Gegners im gesamten Spiel"), outpath = outfolder_shots, filename = paste0("schuesse_gegner_total"))
```


```{r summary statistics, warning=FALSE,message=FALSE, echo=FALSE}

summary_table <- sporttotal_summary_table(pass = pass_tot, shots = shots_tot, shots_opp = shots_opp_tot, pass_areas = pass_areas_tot, pass_space_won_tot = pass_space_won_tot, ecken = ecken, ecken_gegner = ecken_gegner)

# Save spiel, spielrichtung_real and summary table as R object
save(spiel,
  spielrichtung_real,
  pass_tot,
  shots_tot,
  shots_opp_tot,
  pass_areas_tot,
  pass_space_won_tot,
  ecken,
  ecken_gegner,
  summary_table,
  file = paste0(path, "/Statistik/", spiel, ".Rdata")
)

summary_table_single <- summary_table

df_final <- as.data.frame(summary_table)
df_final <- df_final %>% dplyr::mutate_if(is.list, as.character)
```

# Zusammenfassung aller Spiele

```{r combine summary statistics, warning=FALSE,message=FALSE, echo=FALSE}


# Einzelspielanalyse
xlsx::write.xlsx(x = summary_table_single, file = paste0(outfolder, "/", spiel, "_Zusammenfassung_Statistiken.xlsx"), row.names = FALSE)

png(file = paste0(outfolder, "/", spiel, "_Zusammenfassung_Statistiken.png"), height = 880, width = 400)
gridExtra::grid.table(df_final, rows = NULL)
dev.off()


if (plot_all_matches) {
  stat_files <- list.files(path = paste0(path, "/Statistik/"), pattern = "*Rdata", full.names = TRUE)

  load(stat_files[1])
  summary_load <- summary_table
  spiel_load <- spiel
  if (length(stat_files) > 1) {
    for (i in 2:length(stat_files)) {
      load(stat_files[i])
      summary_load <- cbind(summary_load, summary_table[, 2])
      spiel_load <- c(spiel_load, spiel)
    }
  }

  red_match_names <- table_shorten_match_name(match_names = spiel_load)

  colnames(summary_load) <- c("Parameter", red_match_names)
  # Im Seligenporten-Spiel Saison2122 wurden keine Ecken gezählt
  # summary_load[c(nrow(summary_load) - 1, nrow(summary_load)), 2] <- c(NA, NA)

  df_summary_load <- as.data.frame(summary_load)
  df_summary_load <- df_summary_load %>% dplyr::mutate_if(is.list, as.character)

  # Generieren des Outputs in Form von Excel Tabelle und Bilder der Zusammenfassung

  # Zusammenfassung aller Spiele
  # Save table
  xlsx::write.xlsx(x = summary_load, file = paste0(path, "/Statistik/Zusammenfassung/", Sys.Date(), "_Statistiken_kombiniert.xlsx"), row.names = FALSE)

  # For every match add 100 in width
  png(file = paste0(path, "/Statistik/Zusammenfassung/", Sys.Date(), "_Statistiken_kombiniert.png"), height = 880, width = 300 + length(stat_files) * 80)
  gridExtra::grid.table(df_summary_load, rows = NULL)
  dev.off()
}
```
