---
title: "Tracktics Einzelspieleranalyse"
author: "Dr. Jürgen Walther"
date: "12/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(xlsx)
library(dplyr)
library(gridExtra)
library(grid)
library(gtable)
```



```{r combine summary statistics, warning=FALSE,message=FALSE, echo=FALSE}

path <- "C://Users/Juergis/Documents/Fussball/Spielanalyse"


tracktics_files <- list.files(path = paste0(path, "/Tracktics/"), pattern = "*csv", full.names = TRUE)

first_name <- "David"
last_name <- "Drösler"
# Einzelspieler
data_player <- do.call("cbind",lapply(1:(length(tracktics_files)-1), function(i) tracktics_read_player_stats(file = tracktics_files[i], player_first_name = first_name)))


spiele <- list.files(path = paste0(path, "/Tracktics/"), pattern = "*csv", full.names = FALSE)
spiele <- substring(spiele, 1, nchar(spiele)-4)
spiele <- spiele[-length(spiele)]

data_player <- cbind(rownames(data_player), data_player)
rownames(data_player) = NULL

# Ziele definieren
#targets <- tracktics_define_targets(data_tt)
#data_tt <- cbind(data_tt[,1], targets, data_tt[,2:dim(data_tt)[2]])

red_match_names <- table_shorten_match_name(match_names = spiele)

colnames(data_player) <- c("Tracktics Parameter", red_match_names)


df_data_tt <- as.data.frame(data_player)
df_data_tt <- df_data_tt %>% dplyr::mutate_if(is.list, as.character)


# Plot
png(file = paste0(path, "/Tracktics/Einzelspieler/", Sys.Date(), "_", first_name, last_name, ".png"), height = 520, width = 500 + length(tracktics_files) * 40)
table <- tableGrob(df_data_tt, rows = NULL)
title <- textGrob(paste0(first_name, " ", last_name), gp = gpar(fontsize = 40))
padding <- unit(0.5,"line")
table <- gtable_add_rows(
  table, heights = grobHeight(title) + padding, pos = 0
)
table <- gtable_add_grob(
  table, list(title),
  t = 1, l = 1, r = ncol(table)
)
grid.newpage()
grid.draw(table)
dev.off()
```
